# Generated by Django 3.1.4 on 2021-04-12 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0003_auto_20210411_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='actatype',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resultados.address'),
        ),
        migrations.AddField(
            model_name='local',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resultados.department'),
        ),
        migrations.AddField(
            model_name='local',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resultados.district'),
        ),
        migrations.AddField(
            model_name='local',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resultados.province'),
        ),
        migrations.AlterField(
            model_name='department',
            name='ubigeo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='local',
            unique_together={('name', 'address', 'department', 'province', 'district')},
        ),
    ]
