# Generated by Django 3.1.4 on 2021-04-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0004_auto_20210412_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='habiles',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='acta',
            name='votantes',
            field=models.IntegerField(null=True),
        ),
    ]
