# Generated by Django 3.1.4 on 2021-04-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0005_auto_20210412_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='blanco',
            field=models.IntegerField(null=True),
        ),
    ]
