# Generated by Django 3.1.4 on 2021-04-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0006_auto_20210412_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='impugnado',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='acta',
            name='nulo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='acta',
            name='total_votos',
            field=models.IntegerField(null=True),
        ),
    ]
